#!/usr/bin/env bash
# GENERATED by AI
# Simple script to build Docker image and run cargo run inside a container with mounted volumes.
# Prints all output from the build and cargo run process.

set -euo pipefail

REPO_DIR="$(pwd)"
IMAGE_NAME="revm-solution:latest"

echo "================================================"
echo "Building Docker image from ./Dockerfile..."
echo "================================================"
docker build -t "${IMAGE_NAME}" .

echo ""
echo "================================================"
echo "Running 'cargo run --bin solution' inside container"
echo "Container will mount repo at /workspace"
echo "================================================"
docker run --rm -it \
  -v "${REPO_DIR}":/workspace \
  -w /workspace \
  "${IMAGE_NAME}" \
  bash -c "source /root/.bashrc 2>/dev/null; RUST_BACKTRACE=1 cargo run --bin solution"

echo ""
echo "================================================"
echo "Script completed successfully."
echo "================================================" 
